# GEE: Harmonic Regression

```{r}
library(rgee)
library(sf)
ee_Initialize(drive = TRUE)
```

```{r}
source("R/rgee_harmonic_regression.R")

aoi <- read_sf("data/AOI.geojson")
res <- 10000

ndvi1 <- rgee_harmonic_regression(dataset = "NASA/GIMMS/3GV0", dependent = "ndvi", harmonics = 1, 
                                  aoi = aoi, resolution = res, dsn = "data/gee/ndvi_1.tif", mask = -1)
ndvi2 <- rgee_harmonic_regression(dataset = "NASA/GIMMS/3GV0", dependent = "ndvi", harmonics = 2,
                                  aoi = aoi, resolution = res, dsn = "data/gee/ndvi_2.tif", mask = -1)
aet1 <- rgee_harmonic_regression(dataset = "IDAHO_EPSCOR/TERRACLIMATE", dependent = "aet", harmonics = 1,
                                 aoi = aoi, resolution = res, dsn = "data/gee/aet_1.tif")
aet2 <- rgee_harmonic_regression(dataset = "IDAHO_EPSCOR/TERRACLIMATE", dependent = "aet", harmonics = 2,
                                 aoi = aoi, resolution = res, dsn = "data/gee/aet_2.tif")
pr1 <- rgee_harmonic_regression(dataset = "IDAHO_EPSCOR/TERRACLIMATE", dependent = "pr", harmonics = 1,
                                aoi = aoi, resolution = res, dsn = "data/gee/pr_1.tif")
pr2 <- rgee_harmonic_regression(dataset = "IDAHO_EPSCOR/TERRACLIMATE", dependent = "pr", harmonics = 2,
                                aoi = aoi, resolution = res, dsn = "data/gee/pr_2.tif")
tmmn1 <- rgee_harmonic_regression(dataset = "IDAHO_EPSCOR/TERRACLIMATE", dependent = "tmmn", harmonics = 1,
                                  aoi = aoi, resolution = res, dsn = "data/gee/tmmn_1.tif")
tmmn2 <- rgee_harmonic_regression(dataset = "IDAHO_EPSCOR/TERRACLIMATE", dependent = "tmmn", harmonics = 2,
                                  aoi = aoi, resolution = res, dsn = "data/gee/tmmn_2.tif")
tmmx1 <- rgee_harmonic_regression(dataset = "IDAHO_EPSCOR/TERRACLIMATE", dependent = "tmmx", harmonics = 1,
                                  aoi = aoi, resolution = res, dsn = "data/gee/tmmx_1.tif")
tmmx2 <- rgee_harmonic_regression(dataset = "IDAHO_EPSCOR/TERRACLIMATE", dependent = "tmmx", harmonics = 2,
                                  aoi = aoi, resolution = res, dsn = "data/gee/tmmx_2.tif")
```

